'use client'

import { useState } from 'react'
import { Thermometer, Activity, Search, BookOpen, Wrench, Download, MessageSquare, ChevronDown, ChevronUp } from 'lucide-react'
import type { DiagnosisResult, FailureSnapshot } from '@/types'
import { FailureChat } from './FailureChat'

interface FailureCardProps {
  snapshot: FailureSnapshot
  diagnosis: DiagnosisResult | null
  diagnosing: boolean
  statusText?: string
}

const CONF_TONE: Record<DiagnosisResult['confidence'], string> = {
  high: 'nominal',
  medium: 'caution',
  low: 'fault',
}

function exportJSON(snapshot: FailureSnapshot, diagnosis: DiagnosisResult) {
  const blob = new Blob([JSON.stringify({ snapshot, diagnosis, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' })
  const a = document.createElement('a'); a.href = URL.createObjectURL(blob)
  a.download = `whydiditfail-${snapshot.id.slice(0, 8)}.json`; a.click()
}

function exportMarkdown(snapshot: FailureSnapshot, diagnosis: DiagnosisResult) {
  const ts = new Date(snapshot.triggeredAt).toLocaleString()
  const title = diagnosis.failureType.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
  const lines = [
    `# WhyDidItFail — Failure Report`,
    `**Printer:** ${snapshot.printerModel}  `,
    `**Time:** ${ts}  `,
    `**Error:** ${snapshot.errorMessage}  `,
    `**Confidence:** ${diagnosis.confidence}`,
    ``,
    `## Failure Type\n${title}`,
    ``,
    `## Anomaly Detected\n${diagnosis.anomalyDetected}`,
    ``,
    `## Likely Cause\n${diagnosis.likelyCause}`,
    ``,
    `## Fix Steps`,
    ...diagnosis.fixSteps.map((s, i) => `${i + 1}. ${s}`),
    ``,
    `---\n*Generated by WhyDidItFail*`,
  ]
  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  const a = document.createElement('a'); a.href = URL.createObjectURL(blob)
  a.download = `whydiditfail-${snapshot.id.slice(0, 8)}.md`; a.click()
}

export function FailureCard({ snapshot, diagnosis, diagnosing, statusText }: FailureCardProps) {
  const [openChat, setOpenChat] = useState(false)
  const ts = new Date(snapshot.triggeredAt).toLocaleTimeString()
  const d = diagnosis

  const title = d
    ? d.failureType.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    : snapshot.errorMessage

  return (
    <div className="wd-fc">
      <div className="wd-fc__strip" />
      <div className="wd-fc__pad">

        {/* Header */}
        <div className="wd-fc__head">
          <div className="wd-fc__title">
            <span className="wd-fc__ibox">
              <Thermometer size={17} />
            </span>
            <div>
              <p className="wd-fc__h">{title}</p>
              <p className="wd-fc__meta">{ts} · {snapshot.buffer.length} frames · {snapshot.printerModel}</p>
            </div>
          </div>
          {d && (
            <span className={`wd-badge wd-badge--${CONF_TONE[d.confidence]}`}>
              <span className="wd-dot" />{d.confidence} confidence
            </span>
          )}
        </div>

        {/* Diagnosing */}
        {diagnosing && (
          <div className="wd-fc__diagnosing">
            <span className="wd-spin" />
            <span className="wd-fc__statustext">{statusText ?? 'Running LangChain diagnosis…'}</span>
          </div>
        )}

        {/* Diagnosis result */}
        {d && (
          <div className="wd-fc__rows">

            <div className="wd-row">
              <span className="wd-row__i"><Activity size={15} /></span>
              <div>
                <span className="wd-row__l">Anomaly</span>
                <div className="wd-row__b">{d.anomalyDetected}</div>
              </div>
            </div>

            <div className="wd-row">
              <span className="wd-row__i"><Search size={15} /></span>
              <div>
                <span className="wd-row__l">Likely Cause</span>
                <div className="wd-row__b">{d.likelyCause}</div>
              </div>
            </div>

            {d.similarCases.length > 0 && (
              <div className="wd-row">
                <span className="wd-row__i"><BookOpen size={15} /></span>
                <div>
                  <span className="wd-row__l">Similar Cases (knowledge base)</span>
                  <ul className="wd-fc__cases">
                    {d.similarCases.map((c, i) => <li key={i}>{c}</li>)}
                  </ul>
                </div>
              </div>
            )}

            {d.fixSteps.length > 0 && (
              <div className="wd-row">
                <span className="wd-row__i"><Wrench size={15} /></span>
                <div>
                  <span className="wd-row__l">Fix Steps</span>
                  <ol className="wd-fc__steps">
                    {d.fixSteps.map((step, i) => (
                      <li key={i}>
                        <span className="wd-fc__n">{i + 1}</span>
                        <span>{step}</span>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>
            )}

            {/* Export buttons */}
            <div className="wd-fc__exports">
              <button className="wd-btn wd-btn--secondary" onClick={() => exportMarkdown(snapshot, d)}>
                <Download size={13} /> Markdown
              </button>
              <button className="wd-btn wd-btn--secondary" onClick={() => exportJSON(snapshot, d)}>
                <Download size={13} /> JSON
              </button>
            </div>

            {/* Follow-up chat */}
            <div className="wd-fc__followup">
              <button className="wd-fc__toggle" onClick={() => setOpenChat(v => !v)}>
                <span>
                  <MessageSquare size={14} />
                  Ask follow-up questions
                  {openChat && <span className="wd-badge wd-badge--live" style={{ marginLeft: 6 }}>{Math.ceil(0)}</span>}
                </span>
                {openChat ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
              {openChat && <FailureChat snapshot={snapshot} diagnosis={d} />}
            </div>

          </div>
        )}
      </div>
    </div>
  )
}
